#ifndef STDCALL_DEF_H
#define STDCALL_DEF_H

enum SYSCALL_FUNC{SYSCALL_FORK=1, SYSCALL_GETPID, SYSCALL_WRITE, SYSCALL_READ, SYSCALL_INTERRUPTWAIT, SYSCALL_GETPRIORITY, SYSCALL_SETPRIORITY, SYSCALL_MKNOD, SYSCALL_SLEEP};

#endif
