#ifndef STDCALL_DEF_H
#define STDCALL_DEF_H

#define SYSCALL_FORK 0x1
#define SYSCALL_GETPID 0x2
#define SYSCALL_WRITE 0x3
#define SYSCALL_READ 0x4
#define SYSCALL_INTERRUPTWAIT 0x5
#define SYSCALL_GETPRIORITY 0x6
#define SYSCALL_SETPRIORITY 0x7
#define SYSCALL_MKNOD 0x8
#define SYSCALL_SLEEP 0x9

#endif
